<?
$PERM["video"]["*"]="R";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["upload"]["*"]="R";
$PERM["/"]["19"]="T_10";
$PERM["/"]["18"]="R";
$PERM["/"]["*"]="D";
$PERM["about"]["15"]="T_9";
$PERM["company"]["15"]="T_9";
$PERM["pub"]["*"]="R";
?>